wfp-3266 changing scheduled build job

diff --git a/.github/workflows/scheduledBuildJob.yml b/.github/workflows/scheduledBuildJob.yml
--- a/.github/workflows/scheduledBuildJob.yml
+++ b/.github/workflows/scheduledBuildJob.yml
@@ -1,7 +1,7 @@
 name: Scheduled Build Job e2e tests
 on:
   schedule:
-  #  - cron: '0/10 * * * *' # Runs every 10 minutes
+    - cron: '0 1 31 2 *' # Runs every 10 minutes
   workflow_dispatch:        
 permissions:
   contents: read
@@ -9,6 +9,8 @@ jobs:
   e2e-tests:
     runs-on: ubuntu-latest
     steps:
+      - name: Checkout hmpps-manage-a-workforce-ui-e2e-tests 
+        uses: actions/checkout@v5
       - name: Checkout manage-a-workforce-ui
         uses: actions/checkout@v5
         with:
@@ -16,8 +18,6 @@ jobs:
           path: manage-a-workforce-ui
           token: ${{ secrets.GITHUB_TOKEN }}
           ref: main
-      - name: Checkout hmpps-manage-a-workforce-ui-e2e-tests 
-        uses: actions/checkout@v5
       - name: Set up Node.js
         uses: actions/setup-node@v4
         with:
@@ -28,15 +28,20 @@ jobs:
 
       - name: Start manage-a-workforce-ui
         run: |
-          cd manage-a-workforce-ui
           npm install
           npm run build
-          npm run start-external-test
-          npx wait-on http://localhost:3007
-
+          npm run start-external-test &
+        working-directory: manage-a-workforce-ui
       - name: Run docker compose
         run: |
-          docker compose up -d     
+          docker compose up -d  
+      - name: Wait for maw-ui application to be ready
+        run: |
+          for i in {1..60}; do
+            if curl -sSf http://localhost:3007/health; then exit 0; fi
+            sleep 5
+          done
+          echo "App failed to start" && exit 1
 
       #- name: Run e2e tests
         #run: npm run test:regression:chrome
